# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/$VENDOR/$PRODUCTS/pcopy.sh

-include vendor/mediatek/wiko/wiko-vendor-blobs.mk

